"""Report Agent — generates Markdown and JSON review reports."""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

_SEVERITY_ICON = {
    "critical": "[CRITICAL]",
    "high": "[HIGH]",
    "medium": "[MEDIUM]",
    "low": "[LOW]",
}


def _format_finding_md(f: dict) -> str:
    badge = _SEVERITY_ICON.get(f.get("severity", "low"), "[LOW]")
    blocking = " **[BLOCKING]**" if f.get("blocking") else ""
    lines = [
        f"### {badge}: {f.get('title', 'No title')}{blocking}",
        f"",
        f"- **Category**: {f.get('category', 'N/A')}",
        f"- **File**: `{f.get('file_path') or 'N/A'}`",
        f"- **Line**: {f.get('line_number') or 'N/A'}",
        f"- **Confidence**: {f.get('confidence', 0):.0%}",
        f"- **Source**: {', '.join(f.get('source_agents', ['unknown']))}",
        f"",
        f"**Description**: {f.get('description', 'N/A')}",
        f"",
    ]
    if f.get("evidence"):
        lines.append(f"**Evidence**: `{f['evidence']}`")
        lines.append("")
    if f.get("suggestion"):
        lines.append(f"**Suggestion**: {f['suggestion']}")
        lines.append("")
    if f.get("attack_scenario"):
        lines.append(f"**Attack Scenario**: {f['attack_scenario']}")
        lines.append("")
    return "\n".join(lines)


def generate(aggregated_findings: list[dict], llm_findings: list[dict],
             test_generation_result: dict, validation_result: dict) -> dict:
    """Generate Markdown and JSON report from all findings."""
    all_findings = list(aggregated_findings) + list(llm_findings)

    # Categorize
    blocking = [f for f in all_findings if f.get("blocking")]
    critical = [f for f in all_findings if f.get("severity") == "critical" and not f.get("blocking")]
    high = [f for f in all_findings if f.get("severity") == "high"]
    medium = [f for f in all_findings if f.get("severity") == "medium"]
    low = [f for f in all_findings if f.get("severity") == "low"]

    total = len(all_findings)
    summary = (
        f"Review complete. {total} finding(s): "
        f"{len(blocking)} blocking, {len(critical)} critical, "
        f"{len(high)} high, {len(medium)} medium, {len(low)} low."
    )

    # Build Markdown report
    md: list[str] = [
        "# Code Review Report",
        "",
        f"## Summary",
        "",
        summary,
        "",
        "---",
        "",
    ]

    if blocking:
        md.append("## Blocking Issues")
        md.append("")
        for f in blocking:
            md.append(_format_finding_md(f))
        md.append("---")
        md.append("")

    if critical:
        md.append("## Critical")
        md.append("")
        for f in critical:
            md.append(_format_finding_md(f))
        md.append("---")
        md.append("")

    if high:
        md.append("## High Severity")
        md.append("")
        for f in high:
            md.append(_format_finding_md(f))
        md.append("---")
        md.append("")

    if medium:
        md.append("## Medium Severity")
        md.append("")
        for f in medium:
            md.append(_format_finding_md(f))
        md.append("---")
        md.append("")

    if low:
        md.append("## Low Severity")
        md.append("")
        for f in low:
            md.append(_format_finding_md(f))
        md.append("---")
        md.append("")

    if not all_findings:
        md.append("✅ No issues found in this review.")
        md.append("")

    # Test generation summary
    test_plan = test_generation_result.get("test_plan", [])
    if test_plan:
        md.append("## Test Suggestions")
        md.append("")
        for t in test_plan:
            md.append(f"- **{t.get('name', 'Unnamed')}**: {t.get('risk_covered', '')} ({t.get('test_type', 'unit')})")
        md.append("")
        md.append("---")
        md.append("")

    md.append("*Generated by Agent Review System v0.1 (P1 mock LLM mode)*")
    md.append("")

    markdown_report = "\n".join(md)

    json_report = {
        "summary": summary,
        "total_findings": total,
        "blocking_count": len(blocking),
        "critical_count": len(critical),
        "high_count": len(high),
        "medium_count": len(medium),
        "low_count": len(low),
        "findings": all_findings,
        "test_suggestions": test_plan,
    }

    logger.info("Report generated: %d findings.", total)
    return {
        "summary": summary,
        "markdown_report": markdown_report,
        "json_report": json_report,
    }
